services:
  - type: web
    name: whisper-walls-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://srs314848:D09NNXBJwouAGcmw@cluster1.bo8cq1o.mongodb.net/whisper-walls
      - key: JWT_SECRET
        value: SX2BABY